In [22]:
import pandas as pd
import numpy as np
from keras.preprocessing.image import ImageDataGenerator
from keras.models import Sequential
from keras.layers import Conv2D, MaxPooling2D, Input
from keras.layers import Activation, Dropout, Flatten, Dense
from keras.utils import to_categorical
import keras

In [23]:
#Data corresponds to an emotion tag, a 48x48 greyscale picture flattened, and a tag indicating if the image belongs to the test set or the training set.
df = pd.read_csv('./data/fer2013.csv')

train = df[df['Usage']=='Training']
test = df[df['Usage']=='PublicTest']

#TODO: We might want to augment data with ImageDataGenerator 

#TODO: We might want to do some image pre-processing


#Splits data in training and testing, as well as formatting data to right input and output shapes

X_train = np.array(train.pixels.apply(lambda x: np.array(x.split(' ')).reshape(48, 48,1).astype('float32')))
X_test = np.array(test.pixels.apply(lambda x: np.array(x.split(' ')).reshape(48, 48,1).astype('float32')))

#Turn the array of 3D arrays into a 4D array
X_train = np.stack(X_train, axis=0)
X_test = np.stack(X_test, axis=0)

y_train = to_categorical(train['emotion'])
y_test =  to_categorical(test['emotion'])

#Splits off a validation set
#X_val = X_train[-4000:]
#y_val = y_train[-4000:]
#X_train = X_train[:-4000]
#y_train = y_train[:-4000]

print(y_train)

[[1. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 1. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 1. 0. 0.]]


In [18]:
#Define dimensions of input and output layers
D_in = X_train[0].shape
D_out = tuple(y_train[0].shape)
print(D_in)
print(D_out[0])

#Sets up model. To Bobby: Can we make this smarter so you and I can do different models?
model = Sequential()

model.add(Conv2D(32, (3, 3), input_shape=(tuple(D_in))))
model.add(Activation('relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))

model.add(Conv2D(32, (3, 3)))
model.add(Activation('relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))

model.add(Conv2D(64, (3, 3)))
model.add(Activation('relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))


model.add(Dense(D_out[0], activation='softmax'))
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

#TODO: Train networks, evaluate results.

(48, 48, 1)
7


In [19]:
model.summary()

Model: "sequential_3"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_7 (Conv2D)            (None, 46, 46, 32)        320       
_________________________________________________________________
activation_7 (Activation)    (None, 46, 46, 32)        0         
_________________________________________________________________
max_pooling2d_7 (MaxPooling2 (None, 23, 23, 32)        0         
_________________________________________________________________
conv2d_8 (Conv2D)            (None, 21, 21, 32)        9248      
_________________________________________________________________
activation_8 (Activation)    (None, 21, 21, 32)        0         
_________________________________________________________________
max_pooling2d_8 (MaxPooling2 (None, 10, 10, 32)        0         
_________________________________________________________________
conv2d_9 (Conv2D)            (None, 8, 8, 64)         

In [20]:
print('# Fit model on training data')
history = model.fit(X_train, y_train,
                    batch_size=64,
                    epochs=1,
                    # We pass some validation for
                    # monitoring validation loss and metrics
                    # at the end of each epoch
                    #validation_data=(X_val, y_val)
                   )

print('\nhistory dict:', history.history)


# Fit model on training data


ValueError: Error when checking target: expected dense_3 to have shape (4, 4, 7) but got array with shape (7, 1, 1)

In [ ]:
X_train.shape